scas-a-web-1a:
  name: "scas-a-web-1a"
  instance_type: t2.micro
  image_id: ami-1234567890
  vpc_subnet_id: scas-vpc-a-pub-sub-1a

scas-a-app-1a:
  name: "scas-a-app-1a"
  instance_type: t2.micro
  image_id: ami-1234567890
  vpc_subnet_id: scas-vpc-a-priv-sub-1a

scas-b-web-1b:
  name: "scas-b-web-1b"
  instance_type: t2.micro
  image_id: ami-1234567890
  vpc_subnet_id: scas-vpc-b-pub-sub-1b

scas-b-app-1b:
  name: "scas-b-app-1b"
  instance_type: t2.micro
  image_id: ami-1234567890
  vpc_subnet_id: scas-vpc-b-priv-sub-1b
