test-role-1:
  - name: test_role
    managed_policies:
      - arn:aws:iam::aws:policy/AmazonS3TablesReadOnlyAccess
    assume_role_policy_document: {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "Statement1",
          "Effect": "Allow",
          "Principal": {
            "AWS": "arn:aws:iam::166072979266:user/testuser1"
            },
          "Action": "sts:AssumeRole"
        }
      ]
    }

test-role-2:
  - name: test_role_2
    assume_role_policy_document: {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "Statement1",
          "Effect": "Allow",
          "Principal": {
            "AWS": "arn:aws:iam::166072979266:user/testuser2"
            },
          "Action": "sts:AssumeRole"
        }
      ]
    }

s3-ec2-role:
  - name: S3_EC2_Role
    managed_policies:
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
    assume_role_policy_document: {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "Statement1",
          "Effect": "Allow",
          "Principal": {
            "Service": [
              "ec2.amazonaws.com"
            ]
          },
          "Action": "sts:AssumeRole"
        }
      ]
    }

ssm-ec2-role:
  - name: SSM_EC2_Role
    managed_policies:
      - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
    assume_role_policy_document: {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Sid": "AllowEC2AssumeRole",
          "Effect": "Allow",
          "Principal": {
            "Service": [
              "ec2.amazonaws.com"
            ]
          },
          "Action": "sts:AssumeRole"
        }
      ]
    }
