user_list:
  - name: testuser1
    managed_policies:
      - arn:aws:iam::aws:policy/ReadOnlyAccess
  - name: testuser2
    managed_policies:
      - arn:aws:iam::aws:policy/AdministratorAccess
  - name: testuser3
