scas-vpc-a-igw:
  - vpc_id: vpc-0d7e0ccf4886d8351
    region: us-east-1
    tags:
      Name: scas-vpc-a-igw

scas-vpc-b-igw:
  - vpc_id: vpc-050eb3c96d9a42f39
    region: us-east-1
    tags:
      Name: scas-vpc-b-igw
