# VPC A Route Tables
scas-vpc-a-priv-rt-1a:
  - vpc_name: scas-vpc-a
    region: us-east-1
    subnets:
      - scas-vpc-a-priv-sub-1a
    routes: []
    tags:
      Name: scas-vpc-a-priv-rt-1a

scas-vpc-a-priv-rt-1b:
  - vpc_name: scas-vpc-a
    region: us-east-1
    subnets:
      - scas-vpc-a-priv-sub-1b
    routes: []
    tags:
      Name: scas-vpc-a-priv-rt-1b

scas-vpc-a-pub-rt-1a:
  - vpc_name: scas-vpc-a
    region: us-east-1
    subnets:
      - scas-vpc-a-pub-sub-1a
    routes:
      - dest: 0.0.0.0/0
        gateway_id: scas-vpc-a-igw
    tags:
      Name: scas-vpc-a-pub-rt-1a

scas-vpc-a-pub-rt-1b:
  - vpc_name: scas-vpc-a
    region: us-east-1
    subnets:
      - scas-vpc-a-pub-sub-1b
    routes:
      - dest: 0.0.0.0/0
        gateway_id: scas-vpc-a-igw
    tags:
      Name: scas-vpc-a-pub-rt-1b

# VPC B Route Tables
scas-vpc-b-priv-rt-1a:
  - vpc_name: scas-vpc-b
    region: us-east-1
    subnets:
      - scas-vpc-b-priv-sub-1a
    routes: []
    tags:
      Name: scas-vpc-b-priv-rt-1a

scas-vpc-b-priv-rt-1b:
  - vpc_name: scas-vpc-b
    region: us-east-1
    subnets:
      - scas-vpc-b-priv-sub-1b
    routes: []
    tags:
      Name: scas-vpc-b-priv-rt-1b

scas-vpc-b-pub-rt-1a:
  - vpc_name: scas-vpc-b
    region: us-east-1
    subnets:
      - scas-vpc-b-pub-sub-1a
    routes:
      - dest: 0.0.0.0/0
        gateway_id: scas-vpc-b-igw
    tags:
      Name: scas-vpc-b-pub-rt-1a

scas-vpc-b-pub-rt-1b:
  - vpc_name: scas-vpc-b
    region: us-east-1
    subnets:
      - scas-vpc-b-pub-sub-1b
    routes:
      - dest: 0.0.0.0/0
        gateway_id: scas-vpc-b-igw
    tags:
      Name: scas-vpc-b-pub-rt-1b

