scas-vpc-a-priv-sub-1a:
  - vpc_name: scas-vpc-a
    region: us-east-1
    cidr: 10.0.0.0/24
    az: us-east-1a
    tags:
      Name: scas-vpc-a-priv-sub-1a

scas-vpc-a-pub-sub-1a:
  - vpc_name: scas-vpc-a
    region: us-east-1
    cidr: 10.0.1.0/24
    az: us-east-1a
    tags:
      Name: scas-vpc-a-pub-sub-1a

scas-vpc-a-priv-sub-1b:
  - vpc_name: scas-vpc-a
    region: us-east-1
    cidr: 10.0.2.0/24
    az: us-east-1b
    tags:
      Name: scas-vpc-a-priv-sub-1b

scas-vpc-a-pub-sub-1b:
  - vpc_name: scas-vpc-a
    region: us-east-1
    cidr: 10.0.3.0/24
    az: us-east-1b
    tags:
      Name: scas-vpc-a-pub-sub-1b

scas-vpc-b-priv-sub-1a:
  - vpc_name: scas-vpc-b
    region: us-east-1
    cidr: 10.1.0.0/24
    az: us-east-1a
    tags:
      Name: scas-vpc-b-priv-sub-1a

scas-vpc-b-pub-sub-1a:
  - vpc_name: scas-vpc-b
    region: us-east-1
    cidr: 10.1.1.0/24
    az: us-east-1a
    tags:
      Name: scas-vpc-b-pub-sub-1a

scas-vpc-b-priv-sub-1b:
  - vpc_name: scas-vpc-b
    region: us-east-1
    cidr: 10.1.2.0/24
    az: us-east-1b
    tags:
      Name: scas-vpc-b-priv-sub-1b

scas-vpc-b-pub-sub-1b:
  - vpc_name: scas-vpc-b
    region: us-east-1
    cidr: 10.1.3.0/24
    az: us-east-1b
    tags:
      Name: scas-vpc-b-pub-sub-1b
